### PR TITLE
Add Foxes to team listings

### PR DESCRIPTION
**Pull request by Southpaw1496**
It was quite a complex addition using components that I've never used before, so I just thought I'd make sure everything was in order before merging. The build action failed, which is always a good sign, but it did manage to run in my development environment.

### CODE REVIEW

**Review by pluiedev — CHANGES_REQUESTED** [review]
Looks good, although... hummm... the build error looks like an oversight on my part - the code that's erroring out assumes `systemMembers` is a string. Oops! :sweat_smile: Lemme think about how to fix that...

**Comment by Southpaw1496** [comment]
It builds fine on my system, both using `pnpm dev` and `pnpm build` 🤔

**Comment by pluiedev** [comment]
> It builds fine on my system, both using `pnpm dev` and `pnpm build` thinking

That's probably because you already have a PK cache and so the script didn't bother to refresh it - the error only occurs when you try to refresh the cache with 'erroneous' team data

**Comment by Southpaw1496** [comment]
Ah

**Pull request merged**
