### PR TITLE
Fix API page

### PR DESCRIPTION
**Pull request by UpcraftLP**
This PR fixes the api docs page by replacing the previous hackjob with a dedicated swagger-ui package built for astro.

> [!NOTE]  
> Custom CSS seems to be broken, but will have to be fixed at a later date.
Right now having a slightly-bad-looking API page is better than none at all.

---
See preview on Cloudflare Pages: https://preview-232.quiltmc-org.pages.dev

### CODE REVIEW

**Review by Pyrofab — COMMENTED** [review]
Question : will this include the swagger JS on every page ? If so, how heavy is it ?

**Comment by UpcraftLP** [comment]
> Question : will this include the swagger JS on every page ? If so, how heavy is it ?

No, it will not.
It will only load that on the `/api` page

**Review by Pyrofab — APPROVED** [review]

**Comment by Hex4dec** [comment]
Anything blocking this? This has been drafted for a month.

**Comment by Hex4dec** [comment]
I see. How has such an issue not been fixed in a month's time? Surely it should take at most a week.

**Comment by ix0rai** [comment]
quilt is all volunteer work, so we can't expect our contributors to always promptly fix issues. one good thing about open source is that someone else can always pick up the work!

**Comment by UpcraftLP** [comment]
> I see. How has such an issue not been fixed in a month's time? Surely it should take at most a week.

*Surely* it should also not be using an ancient version of astro and ancient versions of dependencies that break if you update, but here we are.

Feel free to check out the changes of this PR and fix the issues with it.

**Comment by Southpaw1496** [comment]
The styling is a bit odd on dark mode, could that be changed?

Screenshot 2024-09-01 at 9 10 47 PM

**Comment by Southpaw1496** [comment]
Ah, I see you've actually addressed the CSS in your original request

Question: The page on https://quiltmc.org/api/ is working fine for me, is there something I'm missing?

**Comment by ix0rai** [comment]
seems like the astro update may have fixed it!

**Comment by Southpaw1496** [comment]
Well, brilliant!

**Pull request closed without merging**
