### PR TITLE
Fix warning message to be less "scary"

### PR DESCRIPTION
**Pull request by woodiertexas**
All I did was make it use the `success` styling found in the "Powerful" message box on the main site. I also was unable to test this locally because of this: https://mclo.gs/wr6vtB4

---
See preview on Cloudflare Pages: https://preview-176.quiltmc-org.pages.dev

### CODE REVIEW

**Comment by ix0rai** [comment]
not a fan. making it green is misleading, and the motion graphic is super annoying. I'd personally like to make the box yellow with #173

**Comment by woodiertexas** [comment]
This was rather annoying to fix ngl:
image

**Review by Pyrofab — APPROVED** [review]
Seems like a good idea, the warning style looks good for this

**Comment by ix0rai** [comment]
imo this looks quite a bit worse on light mode

**Comment by UpcraftLP** [comment]
Seems like this would need to be changed in https://github.com/QuiltMC/quilt-bulma/blob/6a55ad3f40587198959b4c4e28468f6002954344/sass/common/colours.scss#L8 instead.

I think merging this to change the message style from `danger` to `warning` is fine however.

**Pull request closed without merging**
