### PR TITLE
update gdlauncher install page and reorganise install page

### PR DESCRIPTION
**Pull request by ix0rai**
i learned bulma for this

~~gdlauncher development, as well as its PR for quilt support, has been stagnant for nearly a year (the [quilt PR](https://github.com/gorilla-devs/GDLauncher/pull/1400) after receiving absolutely no comment from the gdlauncher developers for a full year), so it doesn't seem like it'll ever be added. with no elements on the "awaiting support" page, we can remove it altogether.~~ GDlauncher has released a big update adding support for quilt

old on right, new on left
image

only real issue with this PR is the wip box being a different size than the buttons which is super annoying but can be fixed later

---
See preview on Cloudflare Pages: https://preview-185.quiltmc-org.pages.dev

### CODE REVIEW

**Comment by ix0rai** [comment]
issues with this pr:
- [ ] mismatched box sizes
- [ ] there should be a limit on buttons per row (I'm thinking 4)

I don't really have the webdev knowhow to fix either

**Comment by woodiertexas** [comment]
i personally think this box should be yellow too:
image

**Comment by KennyDevT** [comment]
GDLauncher added quilt support in The Crabon Rewrite

**Comment by ix0rai** [comment]
hm. if I'm calling the shots here, we'll restore the gdlauncher install page when their carbon version becomes generally available

**Comment by KennyDevT** [comment]
ok

**Comment by KennyDevT** [comment]
Screenshot from 2024-03-22 22-13-50 GDLauncher Carbon has been released with quilt support

**Pull request merged**
