### PR TITLE
clarify and be more neutral with license selection

### PR DESCRIPTION
**Pull request by Hex4dec**
Somebody really loves the MIT license! ;)

---
See preview on Cloudflare Pages: https://preview-236.quiltmc-org.pages.dev

### CODE REVIEW

**Comment by Hex4dec** [comment]
Would be worth considering adding more copyleft licenses like the LGPL (which is NOT the GPL (even though i love it so much), please do your research).

**Comment by ix0rai** [comment]
I don't believe that the new wording is more clear than the original, it seems to me like you're adding more verbosity when we should be keeping descriptions concise if we expect users to read all of them.

**Comment by ix0rai** [comment]
that's not a counter to my point -- I believe the current descriptions communicate the most important points of the licenses, and your changes add more verbosity without adding more clarity

**Comment by Southpaw1496** [comment]
I agree with ix0rai that these changes are overly verbose. Additionally, you say the changes make the wording "more neutral" but I think they're mostly just more confusing. For example, with the MIT license, you've changed "It lets people do anything with your code" to "allows modification and redistribution (including at a fee) requiring attribution. Source code availability not required". Was it previously unclear that "do anything" includes modification, redistribution, or commercial use? Being more explicit without adding any information doesn't make it more clear, it just makes it more difficult to read and harder to choose.

I can see the point that the wording in the page could be improved, but I don't think these changes accomplish the goal of the summaries should be.

**Pull request closed without merging**
