### PR TITLE
Optimize team listings by caching PluralKit requests

### PR DESCRIPTION
**Pull request by pluiedev**
By letting a build script query the PluralKit API and cache the results from that query, we don't have to query the PK API on every rebuild, which ends up massively speeding up the build process.

From this:
Unoptimized version - the site is built in 10.08s

To this:
Optimized version - the site is built in 3.17s

The benefit should be obvious enough.

### CODE REVIEW

**Comment by pluiedev** [comment]
Ugh, looks like Netlify is trying to use Node 16.x again...

**Comment by Southpaw1496** [comment]
Sometimes we intentionally rebuild the site to refresh PluralKit, does this account for that? If not, how often does the script refresh its data?

**Comment by pluiedev** [comment]
> Sometimes we intentionally rebuild the site to refresh PluralKit, does this account for that? If not, how often does the script refresh its data?

You can run `pnpm run clean` to purge the PK cache, and it refreshes the data once every 10 minutes by default.

**Comment by Southpaw1496** [comment]
We're really building stuff more than once every 10 minutes?

**Comment by Southpaw1496** [comment]
Why did you have to put that commit in this PR 😔

**Comment by pluiedev** [comment]
> We're really building stuff more than once every 10 minutes?

Yup - it doesn't just impact final builds, it also impacts dev builds. Although, I think it's reasonable to make it longer

**Comment by pluiedev** [comment]
> Why did you have to put that commit in this PR pensive

Weeeeellll ADCLeo asked for it :>

**Pull request merged**
