### PR TITLE
Astro 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by obj-obj**

### CODE REVIEW

**Comment by gdude2002** [comment]
image

oh god. lmao

---

I guess the thing to do here is check this out locally and play with it? I'll see about doing that when I can.

**Comment by obj-obj** [comment]
Stuff not implemented yet:
- Minecraft versions page
- Navbar on mobile (ill add a javascript-free solution soon™)
- Anything else the cursed typescript does (although I think it just does low contrast and the navbar from looking at it)

**Comment by obj-obj** [comment]
> 

I have 21k deletions lmao

**Comment by gdude2002** [comment]
Have you considered a `.editorconfig` for the indentation?

**Comment by obj-obj** [comment]
> Have you considered a `.editorconfig` for the indentation?

oh yeah I forgor

**Comment by obj-obj** [comment]
PR is ready now

**Comment by obj-obj** [comment]
@gdude2002 merge :)

**Comment by Southpaw1496** [comment]
"PR is ready now" *proceeds to make 5 more commits*

**Comment by obj-obj** [comment]
> "PR is ready now" _proceeds to make 5 more commits_

It wasn't working on windows lmao

**Comment by gdude2002** [comment]
Things are looking good, but I've noticed the following problems:

* A light theme is required for accessibility reasons, and the switching is still not implemented.
* Some of the English copy is wrong - I've noticed missing words in several places, such as the Community page. This needs to be double-checked in full.
* The installation buttons on the client and server installation pages are not implemented. The latest version number is not shown, and the button links are not updated.

Overall, things are looking quite good, but these issues must be fixed before merge.

**Comment by gdude2002** [comment]
Good work, things seem to be more or less in order.

I think the only thing left is that bug that causes the built site to link directly to scss files, right? Can you link the issue here?

**Comment by obj-obj** [comment]
https://github.com/withastro/astro/issues/4395

**Comment by obj-obj** [comment]
Ok pr is *actually* ready now hopefully

**Comment by gdude2002** [comment]
It's starting to seem like someone will need to PR a fix to Astro at this point

**Comment by gdude2002** [comment]
This is going quite well. A few things left, as per discussion on Discord:

- Missing pages in locales other than English should be generated based on the English files, but with Fluent strings taken from the correct locale. This would allow for pages that are just layouts with Fluent strings to be generated correctly, without having to duplicate them across locales without changes.
- Some pages are still missing edit dates that used to have them. Additionally, some layouts contain commented-out Liquid template code. This should be fixed.
- The `README.md` should include more info on how the site should typically be edited. Since web-dev is very much centred around VS Code, the README should include information on where to get it, and how to set it up for site development, including a list of required and recommended extensions.

Overall, I'm quite happy to see where this has been going. Astro is clearly an extremely significant improvement over Jekyll, and I'm excited about getting this into prod. Great work!

**Comment by Southpaw1496** [comment]
Regarding the new README, I think `pnpm dev` and `pnpm build` have an identical output to `pnpm run dev` and `pnpm run build`?

**Comment by gdude2002** [comment]
I think it's time. :rocket:

**Pull request merged**
