### PR TITLE
Possible Refactor to Astro

### PR DESCRIPTION
**Pull request by obj-obj**
Leaving this here as a draft PR, in case anyone looks at PRs here (I need feedback on whether it would be a better choice than Jekyll or not). This isn’t a *merge* request but more as a “is this viable” thing.

Pros/cons list: https://github.com/QuiltMC/quiltmc.org/pull/39#issuecomment-1082027699

Edit: I forgot this was in the branch but also it replaces yarn with pnpm

### CODE REVIEW

**Comment by obj-obj** [comment]
Oh no that's a lot of checks

**Comment by obj-obj** [comment]
image

**Comment by obj-obj** [comment]
@wafflecoffee don't bother reviewing this yet because it's not done

If anything maybe clone and look at the site but reviewing would just be extra work and its not done yet

**Comment by wafflecoffee** [comment]
It's still something to bring to the attention of those two, they're the main people who manage the site now

**Comment by obj-obj** [comment]
Yeah I was just trying to make sure no one wasted time reviewing this lol

**Comment by Southpaw1496** [comment]
Just to have it in one place, what exactly **are** the benefits of Astro compared to Jekyll?

Would switching actually make a large difference to some part of the site, enough to warrant all the developers learning a new system?

**Comment by obj-obj** [comment]
Hmmmmm I wonder why the checks are failing lmao
Screenshot_20220329_083528

**Comment by obj-obj** [comment]
I think its ready for ppl to look at syntax now although blog hasn't been ported and its a few commits out of date

**Comment by obj-obj** [comment]
Oh yeah @Southpaw1496 I forgot to ping you but I made a pro/con list above

**Comment by gdude2002** [comment]
I'm not entirely sure _why_ this PR was created - it kinda feels like your own testbed here, but then again, you could've just done that in your own repo instead of PRing, right?

I'm not personally super interested in the benefits of Astro because none of us are familiar with it - Jekyll is simple, we already have people that know how to use it, and it uses a template language that people already understand (even if liquid kinda sucks, it's familiar).

In #35, I specifically pointed out that we have no plans to move from Jekyll. I pointed out again that it wasn't worth the development effort to switch from something we're familiar with. We're all volunteers, there are very few people that have time to work on this repo, and those that do have very little time in general.

Quilt is preparing for its first beta - this is not the time to be exploring alternatives.

I'm closing this PR not because I don't appreciate the time you've put into this, but to make our intentions clear and to prevent you from spending any more time on something we ultimately were never planning on using.

**Comment by obj-obj** [comment]
> I'm not entirely sure _why_ this PR was created - it kinda feels like your own testbed here, but then again, you could've just done that in your own repo instead of PRing, right?
> 
> I'm not personally super interested in the benefits of Astro because none of us are familiar with it - Jekyll is simple, we already have people that know how to use it, and it uses a template language that people already understand (even if liquid kinda sucks, it's familiar).
> 
> In #35, I specifically pointed out that we have no plans to move from Jekyll. I pointed out again that it wasn't worth the development effort to switch from something we're familiar with. We're all volunteers, there are very few people that have time to work on this repo, and those that do have very little time in general.
> 
> Quilt is preparing for its first beta - this is not the time to be exploring alternatives.
> 
> I'm closing this PR not because I don't appreciate the time you've put into this, but to make our intentions clear and to prevent you from spending any more time on something we ultimately were never planning on using.

I was mainly bored and chose some random thing to work on

**Pull request closed without merging**
