### PR TITLE
Add an RSS feed (#70)

### LINKED ISSUE #70: Regression: RSS feeds are no longer a part of the new website
The old site used the [jekyll-feed](https://github.com/jekyll/jekyll-feed) plugin to generate an RSS feed for the blog, but this functionality is not present in the new Astro site. Possibly [Astro's documentation on RSS feeds](https://github.com/jekyll/jekyll-feed#excerpt-only-flag) would be helpful for setting it up.

### PR DESCRIPTION
**Pull request by Scotsguy**
Closes #70 

Just a really basic feed based on official documentation, but look, it has a description!

image

Same path as the old feed, because everything already points there.

Preview: https://deploy-preview-76--ecstatic-booth-88897a.netlify.app/feed.xml

### CODE REVIEW

**Review by Southpaw1496 — CHANGES_REQUESTED** [review]
Looks good in my RSS reader. I'm not sure if we should have the full articles or just a preview — while I'd prefer full articles myself, I'm not sure what best practice is.

The RSS board's [best practices page](https://www.rssboard.org/rss-profile#element-channel-item-description) says that: 

> An item's description element holds [character data](https://www.rssboard.org/rss-profile#data-types-characterdata) that contains the item's full content or a summary of its contents, a decision entirely at the discretion of the publisher. This element is OPTIONAL if the item contains a [title](https://www.rssboard.org/rss-profile#element-channel-item-title) element.

In which case I think we should go for the full content, as it's more pleasant and reliable, especially if your reader of choice doesn't have parsing functionality.

**Comment by Scotsguy** [comment]
The problem with including the full article content is that you then have to load the full content of every blog post every time you refresh in your newsreader; it makes for a very hefty RSS file after a while.

Plus, we would then have to deal with the idiosyncracies of how newsreaders render our html (relative links, for example, aren't officially defined)

**Comment by Southpaw1496** [comment]
I don't entirely buy the argument about large feed refreshes, especially with the amount of content we generate, but I do see where you're coming from. It's such a weird thing that to account for some types of reader, you have to forego others.

**Comment by gdude2002** [comment]
I buy it, but most feeds only keep a certain number of entries in them to deal with this.

**Comment by Southpaw1496** [comment]
I'd prefer we didn't do that, but, again, I don't think we'll hit the point where we need to for a loooong time

**Comment by Southpaw1496** [comment]
After consideration, I'm happy with the current system

**Review by Southpaw1496 — APPROVED** [review]

**Pull request merged**
