### PR TITLE
Update url used for querying patchnotes

### PR DESCRIPTION
**Pull request by TheEpicBlock**
---
See preview on Cloudflare Pages: https://preview-178.quiltmc-org.pages.dev

### CODE REVIEW

**Review by ix0rai — APPROVED** [review]

**Comment by TheEpicBlock** [comment]
The v1 api was generally order correctly (but fucked up at multiple points, there are snapshots placed completely wrong). The v2 api however lists snapshots before release versions. That's why I pulled in the meta to achieve a proper ordering. This is probably what the launcher does too

**Comment by Southpaw1496** [comment]
Are there any other differences between V1 and V2 that are relevant to our purposes?

**Comment by TheEpicBlock** [comment]
The index file no longer contains the changelogs of each version ever published, those are in separate jsons now (specified by `contentPath` in the index). The code here has already been changed to handle that.

Note that the url for the separate json files is relative to `https://launchercontent.mojang.com/v2/`, but the urls for the images are still relative to `https://launchercontent.mojang.com`

**Comment by simpledemonn** [comment]
I mean if you approve the workflow, we could easily check if anything else changed lol

**Pull request merged**
