### PR TITLE
update mod incompatibility list

### PR DESCRIPTION
**Pull request by ix0rai**
---
See preview on Cloudflare Pages: https://preview-152.quiltmc-org.pages.dev

### CODE REVIEW

**Comment by Southpaw1496** [comment]
I think you need to merge with main before the PR preview will run properly.

**Comment by OroArmor** [comment]
Could we add essentials and the fix for it? https://forum.quiltmc.org/t/complex-solver-error-when-trying-to-launch-the-game/1974/2?u=oroarmor

**Comment by Southpaw1496** [comment]
Please merge with main to incorporate https://github.com/QuiltMC/quiltmc.org/pull/154

**Comment by ix0rai** [comment]
I fixed deeper and darker already lol, this update is pointless

**Pull request closed without merging**
