### PR TITLE
add features page round 2

### PR DESCRIPTION
**Pull request by woodiertexas**
this should have been done a long time ago lmao

---
See preview on Cloudflare Pages: https://preview-242.quiltmc-org.pages.dev

### CODE REVIEW

**Comment by ix0rai** [comment]
2 things:

1.
imo this is really nonsensical to an average user, the website is targeting users not modders
for a features page i'd rather have one or two sentence descriptions for each item, and focus on things that impact players

2.
if we were to put the comparison table on the website, it should be fetched from the QSL github so that it stays up to date

**Comment by woodiertexas** [comment]
> for a features page i'd rather have one or two sentence descriptions for each item, and focus on things that impact players
the thing is, do we actually have things that would encourage players to use quilt?

**Comment by OroArmor** [comment]
> > for a features page i'd rather have one or two sentence descriptions for each item, and focus on things that impact players
> 
> the thing is, do we actually have things that would encourage players to use quilt?

Yes

**Comment by woodiertexas** [comment]
> > > for a features page i'd rather have one or two sentence descriptions for each item, and focus on things that impact players
> > 
> > 
> > the thing is, do we actually have things that would encourage players to use quilt?
> 
> Yes

well, can i get a list of said features so i can put them on this page to replace the table with?

**Pull request closed without merging**
