### PR TITLE
Add team member cards for RTTV and Noah

### PR DESCRIPTION
**Pull request by Southpaw1496**
RTTV and Noah have joined the Mappings Triage team, so I added their cards.

Noah's avatar is a GitHub link by his request (not because I was too lazy to include the raw image).

If this PR goes well, I'm going to start not asking for reviews 🙃

### CODE REVIEW

**Review by wafflecoffee — APPROVED** [review]

**Review by gdude2002 — CHANGES_REQUESTED** [review]
You've committed both Liquid files here without a newline at the end, so you'll need to add that.

Additionally, Noah's Liquid file doesn't have a deep enough indent for the content within the description and links strings.

**Comment by RealRTTV** [comment]
why does it need to have a newline?

**Comment by gdude2002** [comment]
> why does it need to have a newline?

I get asked this literally every time I point it out so I'm just gonna link this: https://stackoverflow.com/a/39331480

**Comment by gdude2002** [comment]
Good stuff, thanks!

**Comment by Southpaw1496** [comment]
I can **hear** that comment.

**Pull request merged**
