### PR TITLE
Initial Process for submitting an emoji

### PR DESCRIPTION
**Pull request by ToffeeMax**
This lays out the process for submitting an emoji for usage within the Quilt discord.

- Lays out contribution process
- Lays out removal

### CODE REVIEW

**Comment by misode** [comment]
This is currently describing the process for submitting and removing your own emojis. What's missing is:
1. The procedure that the community team will follow to accept or reject the emoji addition or removal. If desired, a general community submission procedure should be referenced.
2. A process for someone other than the emoji's author to request the removal of an emoji.

**Comment by ToffeeMax** [comment]
> This is currently describing the process for submitting and removing your own emojis. What's missing is:
> 
> 1. The procedure that the community team will follow to accept or reject the emoji addition or removal. If desired, a general community submission procedure should be referenced.
> 2. A process for someone other than the emoji's author to request the removal of an emoji.

Thanks for these pointers! I have addressed both by

1.  Added a process of "rejection" or "acceptance" of an emoji -- with voting modelled/ tied to RFC 0007
2. 
2. Made it so **any user** can start the removal process

**Comment by gdude2002** [comment]
I think we may be better off figuring out our emoji theme before we push through something like this. I guess I see the value of a process, and community emoji should definitely be put into the art repo, but we don't have anything for our users to template off or design around.

Any ideas for that?

**Comment by varinyc** [comment]
You have a food related emoji capable of facial gestures. Now you need an arbitrary animal or two. Beyond that, inclusion of emotes from similar communities nearby, tends to happen and helps fostor a sense of togetherness. 

Emotes tend to come and go yearly from what I've seen. Loosely drawn from meme-ish culture and community inclusion of (fun) happenstance-events.

I hope this response may help the topic! Even if it may not add a definitive direction.

**Comment by gdude2002** [comment]
Since this PR was created - and I was never convinced it needed to be on the site, for the record - we've created a rich suggestions system directly on Discord.

image

While it's not currently possible to upload images alongside a suggestion, they can easily be added to the thread after the fact, or uploaded to a site like Imgur and linked to as part of the suggestion. I think this is a much better approach than anything that could happen on GitHub - since custom emojis are very much a Discord thing at the moment, and it's much easier to get feedback and present changes in a real-time way.

For that reason, I'll close this PR. Thanks for looking into it regardless, Toffee!

**Pull request closed without merging**
